### ISSUE TITLE
Compare our schema with Magenta's current version, ensure ours aligns to Magenta's schema, clean the unit tests

### ISSUE THREAD

**Issue by kateyang1998** [cc-ar-emr/open-o-previous#178]
After comparing Magenta's current schema (oscarinit_2024.sql) with our oscarinit.sql, I found that the oscarinit_2024.sql file contains more tables that are not present in oscarinit.sql. These tables previously existed separately in oscarinit_on.sql, oscarinit_bc.sql, and initcaisi.sql. Therefore, after replacing oscarinit.sql with oscarinit_2024.sql, we no longer need to call oscarinit_on.sql, oscarinit_bc.sql, and initcaisi.sql, in order to avoid creating the same tables redundantly.

Additionally, two tables in the latest version of the SQL script have had columns added：
- `lst_orgcd` - added `fullcode` and `codeCsv` columns
- `pharmacyInfo` - added `uid` column
Due to the above changes, I had to modify the insert data to these two tables to avoid column count errors when building.

There were two tables removed/deleted:
- `specialty` - I only found it was created in OscarBC15.sql. However, this script has never been called and has been moved to the archive. I'm not sure how it can be created with the previous schema (oscarinit.sql). 
- `formRourke2009` - this table was created in oscarinit_on.sql and oscarinit_bc.sql. However, in the new schema, this table was removed.
I asked Keith to check his database; he confirmed that he didn't have these two tables, either.

The unit tests are running well after implementing the new schema in the alpaca branch (gets 1 error if run tests without building the application after recreating or rebuilding the containers - this is because that file path: /var/lib/OscarDocument is not generated after recreating or rebuilding the containers; therefore the test throw the error since the directory not found. Every time we recreate or rebuild the container, we should build the application first to ensure that all necessary directories are created to avoid failure or error in unit tests)
bullfrog branch is getting more errors: [ERROR] Tests run: 2606, Failures: 319, Errors: 38, Skipped: 0

**Comment by kateyang1998** [comment]
= Update =

All the tests pass in alpaca branch.
I modified the code to create the tmp/OscarDocumentTest directory for testing only, so the test cases in `InboxPopulatingTest` class won't fail due to missing file directory.
The directory will be deleted after running the tests.

**Comment by sebastian-j-ibanez** [comment]
## Update
The `revise-database-schema` branch unit tests has ~ 319 failed tests.

The `revise-database-schema-alpaca` branch only has 1 failed test.

We believe there is a differing Docker setting between the branches that is causing this issue.

**Comment by kateyang1998** [comment]
= Update =

After comparing our database with the schema Keith provided, I found that there are 9 tables missing in our database:
- `LookupCodeValue`
- `formBPMH`
- `formintakea`
- `formintakeb`
- `formintakec`
- `lst_gender_copy_backup`
- `phr_actions`
- `phr_document_ext`
- `phr_documents`

2 tables having different counts of columns:
- `lst_orgcd` - `fullcode` and `codeCsv` columns
- `pharmacyInfo` - `uid` column

2 tables are not using in Magenta's db now:
- `formRourke2009`
- `specialty`

I created a new SQL file - oscarinit_2024.sql, added the 9 missing tables and two updated tables, and dropped the two tables not used now. No change applies to the tables in the existing SQL files. oscarinit_2024.sql is only used to patch.

The application was built and ran successfully with the new implementation. The unit tests worked properly with this approach in both alpaca and bullfrog branches.

**Comment by kateyang1998** [comment]
= Update =
After discussing and comparing our schema with Magenta's current version, I made below modifications:
- Changed our db engine from `Aria` to `InnoDB`
- Altered tables missing constraints, and keys
- Altered tables having different column sequences
- Altered columns having different varchar length

Tables using Aria engine in Magenta’s db: 
- `DHIRSubmissionLog`
- `DocumentExtraReviewer`
- `EFormDocs`
- `HrmLog`
- `HrmLogEntry`
- `ISO36612`
- `OLISQueryLog`
- `OLISResults`
- `PreventionReport`
- `SystemPreferences`
- `billing_preferences`
- `consultationRequestExtArchive`
- `consultationRequestsArchive`
- `document_review`
- `emailAttachment`
- `emailConfig`
- `emailLog`
- `erefer_attachment`
- `erefer_attachment_data`
- `formRourke2017`
- `formRourke2020`
- `form_boolean_value`
- `incomingLabRulesType`
- `lst_gender_copy_backup`
- `msgIntegratorDemoMap`
- `rbt_groups`
- `read_lab`
Open to discuss: should Magenta change the engine to InnoDB?

Table missing key in Magenta's db:
- `radetail` - KEY `service_date_index` (`service_date`)
Open to discuss: should Magenta add the key?

Difference still exists:
Magenta's current client charset is `utf8mb4`, while ours is `utf8`
